name: 'Generate sBOM'
description: 'Generate and upload an sBOM of the service'
inputs:
  dir-path:
    description: 'The root directory containing the build or lock files.'
    default: ./
  sbom-format: 
    description: 'Format of the generated sBOM (cyclonedx-json, spdx-json)'
    default: 'cyclonedex-json'



runs:
  using: 'composite'
  steps:  
    - uses: actions/checkout@v3
    
    - uses: AppThreat/cdxgen-action@v1
      with:
        output: ./bom.json

    - uses: actions/upload-artifact@v3
      with:
        path: bom.json

   
        


  