name: 'Generate sBOM'
description: 'Generate and upload an sBOM of the service'
inputs:
  dir-path:
    description: 'The root directory containing the build or lock files.'
    default: ./
  sbom-format: 
    description: 'Format of the generated sBOM (cyclonedx-json, spdx-json)'
    default: 'cyclonedx-json'

outputs:
  generated-sbom:
    description: 'The generated sBOM file'
    value: ${{ steps.generate-sbom.output }}


runs:
  using: 'composite'
  steps:  
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build
      shell: bash

    - name: Generate sBOM
      id: generate-sbom
      uses: anchore/sbom-action@v0
      with:
        path: ./
        format: ${{ inputs.sbom-format }}
        artifact-name: ${{ github.repository }}-${{ github.sha }}.json

  
   
        


  